- name: Create nginx config directory
  file:
    path: "{{app_base_dir}}/nginx"
    state: directory

- name: Generate nginx.conf
  template:
    src: nginx.conf.j2
    dest: "{{app_base_dir}}/nginx/nginx.conf"

  notify: Restart nginx container
