- name: Run nginx reverse proxy container
  community.docker.docker_container:

    name: nginx-{{ env }}-proxy

    image: nginx:alpine

    state: started
    restart_policy: always
    recreate: true

    ports:
      - "{{ nginx_http_port }}:80"
      - "{{ nginx_https_port }}:443"

    networks:
      - name: "{{ docker_network }}"

    volumes:
      - "{{app_base_dir}}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
