- name: Create global nginx directory
  ansible.builtin.file:
    path: "{{ global_nginx_dir }}"
    state: directory
    mode: "0755"


- name: Deploy global nginx configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ global_nginx_dir }}/nginx.conf"
    mode: "0644"
  notify: Restart global nginx


- name: Deploy global nginx compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ global_nginx_dir }}/docker-compose.yml"
    mode: "0644"


- name: Start global nginx
  community.docker.docker_compose_v2:
    project_src: "{{ global_nginx_dir }}"
    state: present
    recreate: auto