- name: Install certbot
  apt:
    name: certbot
    state: present
    update_cache: true

- name: Stop global-nginx if running
  service:
    name: global-nginx
    state: stopped
  ignore_errors: true

- name: Generate or Update SSL certificates
  command: >
    certbot certonly
    --standalone
    --non-interactive
    --agree-tos
    --expand
    --cert-name {{ certbot_cert_name }}
    --email {{ certbot_email }}
    {% for domain in certbot_domains %}
    -d {{ domain }}
    {% endfor %}

  args:
    creates: "/etc/letsencrypt/live/{{ certbot_domains[0] }}/fullchain.pem"

  always:
    - name: Start global-nginx
      service:
        name: global-nginx
        state: started
        enabled: true
