---
- name: Install certbot
  ansible.builtin.apt:
    name: certbot
    state: present
    update_cache: true

- name: Generate or update SSL certificates
  block:

    - name: Stop global-nginx
      community.docker.docker_container:
        name: global-nginx
        state: stopped

    - name: Generate or update certificates
      ansible.builtin.command: >
        certbot certonly
        --standalone
        --non-interactive
        --agree-tos
        --expand
        --cert-name {{ item.cert_name }}
        --email {{ certbot_email }}
        {% for domain in item.domains %}
        -d {{ domain }}
        {% endfor %}
      loop: "{{ certbot_certificates }}"
      loop_control:
        label: "{{ item.cert_name }}"

  always:

    - name: Start global-nginx
      community.docker.docker_container:
        name: global-nginx
        state: started