backend_apps:
  # fuelman api application configuration
  #  add app specific variables here and also in roles/backend/tasks/main.yml
  fuelman-api:
    backend_name: "fuelman-api"

    backend_repo: "git@github.com:maargali/fuelman.git"

    backend_container_name: fuelmanAppProd
    backend_image_name: prod-fuelman-app

    backend_host_port: 8080
    app_name: fuelman
    app_jar_file: "target/fuelman-1.0.0.jar"

    backend_schema: fman

    backend_java_opts: >-
      -Dspring.profiles.active=prod
      -Dlogging.level.root=INFO
      -Dfleet.endpoint.url=https://your-api-url
      -Dapp.database.url=jdbc:postgresql://{{ postgres_container_name }}:{{ postgres_port }}/{{ postgres_db }}?currentSchema={{ backend_schema }}&options=-ctimezone=Asia/Kolkata
      -Dapp.database.user={{ postgres_user }}
      -Dapp.database.pass={{ postgres_password }}
      -Duser.timezone=Asia/Kolkata

  # anchor api application configuration
  # add app specific variables here and also in roles/backend/tasks/main.yml
  anchor-api:
    backend_name: "anchor-api"

    backend_repo: "git@github.com:maargali/anchor.git"

    backend_container_name: prod-anchor-app
    backend_image_name: prod-anchor-app

    backend_host_port: 9080
    
    app_name: anchor
    app_jar_file: "target/anchor-1.0.0.jar"

    backend_schema: fman

    backend_java_opts: >-
      -Dspring.profiles.active=prod
      -Dlogging.level.root=INFO
      -Dfuelman.endpoint.url=http://fuelmanAppProd:8080/anchorApi
      -Dapp.database.url=jdbc:postgresql://{{ postgres_container_name }}:{{ postgres_port }}/{{ postgres_db }}?currentSchema={{ backend_schema }}&options=-ctimezone=Asia/Kolkata
      -Dapp.database.user={{ postgres_user }}
      -Dapp.database.pass={{ postgres_password }}
      -Duser.timezone=Asia/Kolkata

  # fleet api application configuration
  # add app specific variables here and also in roles/backend/tasks/main.yml
  fleet-api:
    backend_name: "fleet-api"

    backend_repo: "git@github.com:maargali/fleet_owner.git"

    backend_container_name: prod-fleet-app
    backend_image_name: prod-fleet-app

    backend_host_port: 7080

    backend_schema: fleets

    app_name: fleetowner
    app_jar_file: "target/fleetowner-1.0.0.jar"

    backend_java_opts: >-
      -Dspring.profiles.active=prod
      -Dlogging.level.root=INFO
      -Dfuelman.endpoint.url=https://your-api-url
      -Dapp.database.url=jdbc:postgresql://{{ postgres_container_name }}:{{ postgres_port }}/{{ postgres_db }}?currentSchema={{ backend_schema }}&options=-ctimezone=Asia/Kolkata
      -Dapp.database.user={{ postgres_user }}
      -Dapp.database.pass={{ postgres_password }}
      -Duser.timezone=Asia/Kolkata
