certbot_certificates:
  - cert_name: fuelman.in
    domains:
      - fuelman.in
      - www.fuelman.in

  - cert_name: anchor.fuelman.in
    domains:
      - anchor.fuelman.in

  - cert_name: fleet.fuelman.in
    domains:
      - fleet.fuelman.in

certbot_email: maargali.company@gmail.com



